import type { Producto } from "./tipos";

// SCRUM-31 (Camilo) — Datos de prueba mientras el backend (rama back-end) no
// expone el endpoint real de productos. Reemplazar por un fetch a la API
// cuando el equipo defina el contrato (ver nota en BusquedaCatalogo.tsx).
export const productosMock: Producto[] = [
  {
    id: 1,
    codigo: "ELEC-001",
    nombre: "Audífonos Bluetooth X200",
    descripcion: "Audífonos inalámbricos con estuche de carga",
    categoria: "Electrónica",
    unidadMedida: "Unidad",
    precioCompra: 58400,
    precioVenta: 89900,
    stockActual: 12,
    stockMinimo: 5,
    estado: "Activo",
  },
  {
    id: 2,
    codigo: "ELEC-002",
    nombre: "Cargador USB-C 20W",
    descripcion: "Cargador rápido para celular",
    categoria: "Electrónica",
    unidadMedida: "Unidad",
    precioCompra: 22800,
    precioVenta: 35000,
    stockActual: 0,
    stockMinimo: 10,
    estado: "Activo",
  },
  {
    id: 3,
    codigo: "ELEC-003",
    nombre: "Cable HDMI 2 metros",
    descripcion: "Cable HDMI de alta velocidad",
    categoria: "Electrónica",
    unidadMedida: "Unidad",
    precioCompra: 11700,
    precioVenta: 18000,
    stockActual: 40,
    stockMinimo: 15,
    estado: "Inactivo",
  },
  {
    id: 4,
    codigo: "ROPA-001",
    nombre: "Camiseta algodón unisex",
    descripcion: "Camiseta básica manga corta, varias tallas",
    categoria: "Ropa",
    unidadMedida: "Unidad",
    precioCompra: 16200,
    precioVenta: 25000,
    stockActual: 30,
    stockMinimo: 10,
    estado: "Activo",
  },
  {
    id: 5,
    codigo: "ROPA-002",
    nombre: "Gorra deportiva",
    descripcion: "Gorra ajustable con visera curva",
    categoria: "Ropa",
    unidadMedida: "Unidad",
    precioCompra: 13000,
    precioVenta: 20000,
    stockActual: 0,
    stockMinimo: 8,
    estado: "Activo",
  },
  {
    id: 6,
    codigo: "FERR-001",
    nombre: "Martillo de uña 16oz",
    descripcion: "Mango de fibra de vidrio",
    categoria: "Ferretería",
    unidadMedida: "Unidad",
    precioCompra: 20800,
    precioVenta: 32000,
    stockActual: 7,
    stockMinimo: 3,
    estado: "Activo",
  },
  {
    id: 7,
    codigo: "FERR-002",
    nombre: "Cinta métrica 5m",
    descripcion: "Cinta métrica con freno",
    categoria: "Ferretería",
    unidadMedida: "Unidad",
    precioCompra: 9800,
    precioVenta: 15000,
    stockActual: 22,
    stockMinimo: 5,
    estado: "Activo",
  },
  {
    id: 8,
    codigo: "PAPE-001",
    nombre: "Resma de papel carta",
    descripcion: "Papel bond 75g, 500 hojas",
    categoria: "Papelería",
    unidadMedida: "Resma",
    precioCompra: 14300,
    precioVenta: 22000,
    stockActual: 15,
    stockMinimo: 5,
    estado: "Activo",
  },
  {
    id: 9,
    codigo: "PAPE-002",
    nombre: "Caja de esferos x12",
    descripcion: "Esferos de tinta negra",
    categoria: "Papelería",
    unidadMedida: "Caja",
    precioCompra: 7800,
    precioVenta: 12000,
    stockActual: 0,
    stockMinimo: 4,
    estado: "Inactivo",
  },
  {
    id: 10,
    codigo: "HOG-001",
    nombre: "Juego de vasos x6",
    descripcion: "Vasos de vidrio 300ml",
    categoria: "Hogar",
    unidadMedida: "Juego",
    precioCompra: 18200,
    precioVenta: 28000,
    stockActual: 9,
    stockMinimo: 3,
    estado: "Activo",
  },
  {
    id: 11,
    codigo: "HOG-002",
    nombre: "Toalla de cocina",
    descripcion: "Toalla absorbente 40x60cm",
    categoria: "Hogar",
    unidadMedida: "Unidad",
    precioCompra: 5800,
    precioVenta: 9000,
    stockActual: 18,
    stockMinimo: 6,
    estado: "Activo",
  },
  {
    id: 12,
    codigo: "ELEC-004",
    nombre: "Power bank 10000mAh",
    descripcion: "Batería portátil con doble puerto USB",
    categoria: "Electrónica",
    unidadMedida: "Unidad",
    precioCompra: 42200,
    precioVenta: 65000,
    stockActual: 3,
    stockMinimo: 5,
    estado: "Activo",
  },
];
